<cffunction name="get_super"><!--- Get Supervisors to CC on Delegations --->
	<cfargument name="oprid" required="yes">
    <cfquery name="super_id" datasource="#application.ods#">
		SELECT sprvsr_empl_nmbr as sup_id from empl_ckis
		where oprtr_id='#oprid#'
	</cfquery>
	<cfquery name="sup_oprid" datasource="#application.ods#">
		Select oprtr_id from empl_ckis
		where empl_nmbr='#super_id.sup_id#'
	</cfquery>
    <cfif sup_oprid.oprtr_id NEQ "">
		<cfset sup_email='#sup_oprid.oprtr_id#' & '@hii-tsd.com'>
	<cfelse>
		<cfset sup_email="">
	</cfif>
	<cfreturn sup_email>
</cffunction>
<cfquery name="getDelegateToEmail" datasource="#application.dsn#">
		Select oprid,email from v_users
		where oprid=#delegateTo_oprid#
	</cfquery>
<cfset To="#getDelegateToEmail.email">

<cfquery name="getDelegateFromEmail" datasource="#application.dsn#">
		Select oprid,email from v_users
		where oprid=#delegateFrom_oprid#
	</cfquery>
<cfset CC="#getDelegateFromEmail.email">
<cfset tor_super=#get_super(delegateFrom_oprid)#>
<cfif (sup_Email NEQ "") AND (NOT find(sup_email,cc))><cfset CC="#cc#" & "," & "#sup_email#"></cfif>
<cfset tee_super=#get_Super(delegateTo_oprid)#>
<cfif sup_Email NEQ "" AND (NOT find(sup_email,cc))><cfset CC="#cc#" & "," & "#sup_email#"></cfif>
<cfset From="ARA@hii-tsd.com">  
<cfoutput>
<cfinclude template="Msg_HdrStyle.cfm">
<!--- HTML for Distribution List: Stored in PDF --->
<cfset MsgDist="
<table width='100%' border='0' cellspacing='0' cellpadding='0'>
   <tr>
      <td width='34' class='spacer'>&nbsp;</td>
      <td align='left'>
                  
                  <table width='560' border='0' cellspacing='0' cellpadding='0'>
                     <tr>
                        <td class='detail'>
                           
                           <table width='560' border='0' cellspacing='10' cellpadding='0' class='post'>
                              <tr>
                                 <td class='detail'>
								 From:&nbsp;&nbsp;&nbsp;#From#<br>
								 To: &nbsp;&nbsp;&nbsp;#TO#<br>
								 CC: &nbsp;&nbsp;&nbsp;#CC#<br>
								 Subject: &nbsp;&nbsp;&nbsp;#subject#<br><br>
								 </td></tr>
							</table>
					</td></tr></table>
</td></tr></table>
">

<cfset MsgBody="
<table width='100%' border='0' cellspacing='0' cellpadding='0'>
   <tr>
      <td width='34' class='spacer'>&nbsp;</td>
      <td align='left'>
         
         <table width='560' border='0' bgcolor='##4b5c63' cellspacing='0' cellpadding='0'>
            <tr>
               <td bgcolor='##7995a2' colspan='3'>
                  <p class='ariva' >ARA Delegation Notification .... #dateformat(Now(),'MM/DD/yy')# #timeformat(now(),'hh:mm tt')# </p>
				  <p class='tag'>#shortDesc#</p>
                  
               </td>
            </tr>
            <tr>
               <td width='560' valign='top'>
                  
                  <table width='560' border='0' cellspacing='0' cellpadding='0'>
                     <tr>
                        <td class='detail'>
                           
                           <table width='560' border='0' cellspacing='10' cellpadding='0' class='post'>
                              <tr>
                                 <td class='detail'>
                                    <p>#MsgText#</p>
                                 
                                    </td>
                              </tr>
                           </table>
                           
                        </td>
                     </tr>
  
                     <tr>
                        <td>&nbsp;</td>
                     </tr>
          
					 <tr>
					 <td class='detail'>
					  <table width='560' border='0' cellspacing='10' cellpadding='0' class='post'>
                              <tr>
                                 <td class='detail'>
					
					 	<font class='footnote'>This message is automatically generated by the ARA system, and is not intended for reply.</font>

						</td></tr></table>
					</td></tr>
                  </table>
                  
               </td>
               
            </tr>
         </table>
         
      </td>
   </tr>
</table>

</body>
</html>
">
	
</cfoutput>
<!--- Mail it --->
<cfinclude template="mail_sendit.cfm">
