<cfif isDefined('url.aid')>
	<cfset id_ara="#decrypt(url.AID,request.encryptkey,request.encrypttype,'hex')#">
<cfelse>
	<cfset id_ara=8>
</cfif>
<cfset IsPrint="Yes">
<cfoutput>

<!--- ++++++++++++++ Functions to Include +++++++++++++++++++++  --->
<!--- +++++++++++ Pulls ARA, user, groups, sector, category, status ++++++++++ --->
<cfinclude template="../../model/m_ara/qry_ara.cfm">

<cfinclude template="../../model/m_ara/qry_controller.cfm">
<!--- QRY_AttachInfo: <cfset info=#DocInfo()# inits empty vars. #DocInfo(id_attachment)# inits vars for existing attachment --->
<cfinclude template="../../model/m_forms/qry_attachinfo.cfm">
<cfinclude template="../../model/m_forms/qry_AttachmentStatus.cfm">
<br>
</cfoutput>

<cfdocument filename="#application.PDFDir#/ARADocument-#id_ara#.pdf"   margintop="1" marginleft=".50" marginbottom="1" marginright=".50" format="PDF" backgroundvisible="yes" overwrite="yes" pageType="letter" unit="in"  localURL="yes">
	<style type="text/css">
	p {
	font-family: Trebuchet MS,sans-serif;
	color: #222222;
	font-size:9pt;
	line-height:12pt;
	}
	li {
	font-family: Trebuchet MS,sans-serif;
	color: #222222;
	font-size:9pt;
	line-height: 12pt;
	}
	fieldset {
	border-solid;
	border-width: 1pt;
	border-color: #AAAAAA;
	}
	
	.bordera, .borderq, .border {
	border-style: solid;
	border-width: 1px;
	border-color: #EEEEEE;
	font-family:Trebuchet MS, sans-serif;
	/* color: #222222; */
	color:orange;
	font-size: 9pt;
	line-height:13pt;
	letter-spacing:3em;
	font-family: Arial;
	}
	
	.smtitle {
	font-family: Arial, sans-serif;
	color: #758B5A;
	font-size: 8pt;
	text-transform: uppercase;
	margin-bottom:0px; 
	padding-bottom:0px;
	letter-spacing:1px;
	}
	.doc {
		font-family: verdana, Avant Garde,sans-serif;
		font-size: 9pt;
		font-weight: normal;
		font-style: normal;
		vertical-align:middle;
		color: #333333;
		margin:5pt 5pt 2pt -20pt;
		line-height:15pt; 
		list-style-image: url(SmDocBlue.png);
}
 .grad {
		background-color:#a8c399;
		background-repeat: repeat-x;
		border-style: solid;
		border-width: 1px;
		border-color: #cccccc;
		font-family: Arial,sans-serif;
		color:#FFFFFF;
		font-size: 9pt;
}
.qnum {
font-family: Trebuchet MS, arial, sans-serif;
font-size: 9pt;
color: #22222;
width:15px;
border: solid 1px #EEEEEE;
TEXT-ALIGN: center;
}
.grey {
font-family: Trebuchet MS, arial, sans-serif;
font-size: 9pt;
color: #bbbbbb;
border: solid 1px #CCCCCC;
}
.greyblue {
background-color:#777777;
color:white;
font-family: Trebuchet MS, verdana,sans-serif;
font-size:9pt;

}
.outerborder {
border: solid 1px #222222;
}
.numblock {
font-family: Georgie,serif;
color: #ffffff;
background-color: #444444;

padding:0px 2px 0px 5px;
}
 .tiny {
 font-family: Arial, sans-serif;
 font-size:9pt;
 }

	.x {
	font-family:  Arial,sans-serif;
	color: #222222;
	font-size: 9pt;
	}
	.title {
	font-family: Georgia, serif;
	color: #567d9d;
	font-size: 16pt;
	font-style:bold;
	padding: 0pt 0pt 10pt 0pt;
	}
	.title2 {
  font-family: Georgia, serif;
  color:#222222;
  font-size: 14px;
  margin: 30px 0px 10px 0px;
  font-weight: Normal;
  }
  .subtitle {
 font-family: Georgia, serif;
 color:#758B5A;
 font-size: 12pt;
 padding: 5px 0px 5px 0px;
 font-weight: bold;
 }
 .dollar {
font-family: verdana, arial, sans-serif;
font-size: 11px;
color: #2b3438;
border: solid #cccccc 1px;
text-align:right;
padding-right:50px;
}
	A.embed {color: #222222; text-decoration: none;}
A.embed:link {color: #222222; text-decoration: none;}
A.embed:active {color: #222222; text-decoration: none;}
A.embed:visited {color: #222222; text-decoration: none;}
A.embed:hover {color: #222222; text-decoration: none;color: #758B5A; }
</style>
<!--- +++++++++++++++++  HEADER +++++++++++++++++++++ --->
	<cfdocumentItem type= "header">
	   <cfoutput>
	   <style type="text/css">
		.x {font-family: Arial, sans-serif; font-size: 9pt; width: 100%;}
		</style>
	   <table  cellpadding=5 border=0 width=100%>
	   <tr>
	   <td  width=20%>
	   <p class="x">Generated by ARA</p>

	   </td>
	   <td  class="x" align="center" width=60%>&nbsp;
	   </td>
	   <td  class="x" align="right" width=20%> 
	  #dateformat(now(),"MMMM DD, YYYY")#
	   </td></tr></table>
	   </cfoutput>
	</cfdocumentitem>
<!--- +++++++++++++++++  Footer +++++++++++++++++++++ --->
	<cfdocumentItem type= "footer">
		<style type="text/css">
		.x {font-family: Arial, sans-serif; font-size: 9pt;}
		</style>
	   <cfoutput>
	
	   <table  cellpadding=5 width=100%>
	   <tr>
	   <td class="x" width=33%>
	   
	   ARA #reference# Details
	   </td>
	   <td  class="x" align="center" width=33%>HII Confidential and Proprietary</td>
	   <td  class="x" align="center" width=33%> 
	   Page #cfdocument.currentpagenumber# of #cfdocument.totalpagecount#
	   </td></tr></table>
	   </cfoutput>
	</cfdocumentitem>
	<table width=100% cellpadding=0 cellspacing=0>
	<tr>
	<td align="center">
	<cfoutput>
		<font style="font-family:Georgia;font-size:13pt;line-height: 17pt;color:##222222;">ARA #Reference#,  Customer: #customerName#</font>
		<font style="font-family:Trebuchet MS;font-size:9pt;line-height: 11pt;color:##777777;"><br>Title: #title#<br>
		Sector: #sector#, Category: #catName#, Total Amount: #dollarformat(amountTotal)#</font><br><br>
	</cfoutput>
	</td></tr></table>
	<cfoutput>
	<p class="title2"><font class="numblock"> 1. </font> &nbsp;&nbsp;ARA Summary</p>
	<cfinclude template="dsp_ARA_top_summary.cfm">
	
	<p class="title2"><font class="numblock"> 2. </font> &nbsp;&nbsp;Program Manager Input</p>
	<cfinclude template="dsp_ARA_PM_View.cfm">
	<cfdocumentitem type = "pagebreak"/>
	<p class="title2"><font class="numblock"> 3. </font> &nbsp;&nbsp;Contract Administrator Input</p>
	<cfinclude template="dsp_ARA_ContractInfo_View.cfm">
	<cfdocumentitem type = "pagebreak"/>
	
    <p class="title2"><font class="numblock"> 4. </font> &nbsp;&nbsp;Controller Input</p>
	<cfinclude template="dsp_ARA_ControllerV2_view.cfm">
    <cfdocumentitem type = "pagebreak"/>
	<p class="title2"><font class="numblock"> 5. </font> &nbsp;&nbsp;Supporting Documentation</p>
	<cfinclude template="dsp_ARA_docs_View.cfm">
    
    <cfdocumentitem type = "pagebreak"/>
	<p class="title2"><font class="numblock"> 6. </font> &nbsp;&nbsp;Approval Log</p>
	<cfinclude template="dsp_ARA_approvals_View.cfm"></cfoutput>
    <!--- cfdocumentitem type = "pagebreak"/ --->
	<p class="title2"><font class="numblock"> 7. </font> &nbsp;&nbsp;Notes</p>
	<cfset formorview="view">
	<cfinclude template="dsp_ARA_note_view.cfm">
	
	
</cfdocument>
<cflocation url="temp/ARADocument-#id_ara#.pdf##page=1&zoom=100">	