
<cfset to="#gUsers.email">
<cfset From="ARA@hii-tsd.com">  
<cfset subject="ARA Account info for #gUsers.empname#">
<cfoutput>
<cfset Message="
<html>
<head>
   <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>
   <title>ARA User Account</title>
   <style type='text/css' media='screen'>
      body {
         margin: 0;
         padding: 0;
         background-color: ##FFFFFF;
      }
	a
	{color: ##FFFFFF; text-decoration: underline;}
      
	.detail {
	background-color: ##4b5c63;
	font-family: Trebuchet MS, helvetica,sans-serif;
	color: ##ffffff;
	font-size: 11px;
	line-height: 14px;
	}
      .ariva {
         font-family: georgia;
         font-size: 16px;
         font-weight: normal;
         color: ##ffffff;
		 letter-spacing:0px;
         margin: 10px 10px 0px 10px;
         padding:10px 10px 10px 10px;
      }
	  .tag {
         font-family: Trebuchet MS, helvetica,sans-serif;
         font-size: 13px;
         font-weight: normal;
         color: ##ffffff;
		 text-transform:uppercase;
		 letter-spacing:0px;
         margin: 0;
         padding:0px 0px 0px 10px;
		 margin: 0px 0px 10px 10px;
      }


      .title {
	   	font-family: Trebuchet MS, helvetica,sans-serif;
         font-size: 13px;
         font-weight: normal;
         color: ##ffffff;
		 text-transform:uppercase;
         background-color: ##000000;
         padding: 2px 10px 4px 10px;
      }
	.footnote {
	font-family: verdana,sans-serif;
	font-size: 10px;
	color: ##FFFFFF;
	background-color:##4b5c63;
	text-align:center;
	margin:10px;
	padding:10px;
	}
   </style>

</head>
<body>
<table width='100%' border='0' cellspacing='0' cellpadding='0'>
   <tr>
      <td width='34' class='spacer'>&nbsp;</td>
      <td align='left'>
         
         <table width='560' border='0' bgcolor='##4b5c63' cellspacing='0' cellpadding='0'>
            <tr>
               <td bgcolor='##7995a2' colspan='3'>
                  <p class='ariva' >ARA User Account .... #dateformat(Now(),'MM/DD/yy')# #timeformat(now(),'hh:mm tt')# </p>
				  <p class='tag'>Your ARA User Account Added or Updated</p>
                  
               </td>
            </tr>
            <tr>
               <td width='560' valign='top'>
                  
                  <table width='560' border='0' cellspacing='0' cellpadding='0'>
                     <tr>
                        <td class='detail'>
                           
                           <table width='560' border='0' cellspacing='10' cellpadding='0' class='post'>
                              <tr>
                                 <td class='detail'>
                                    <p>Your account on the ARA system has been added or updated:</p>
									<p>Name: #empname#<br>
									Sector, Group: #gUsers.GroupName#, #gUsers.SectorName#<br>
									Operation, Division: #ods_Opname#, #ods_divName#
									ARA Job Title: #gUsers.title#<br>
									ARA Security Level: #gUsers.roleName#</p>
									
                                    </td>
                              </tr>
                           </table>
                           
                        </td>
                     </tr>
  
                     <tr>
                        <td>&nbsp;</td>
                     </tr>
          
                     <!-- tr>
                        <td height='4' bgcolor='##7995a2'></td>
                     </tr>
					  <tr>
			
                        <td class='detail'>
						<table width='560' border='0' cellspacing='10' cellpadding='0' class='post'>
                              <tr>
                                 <td class='detail'>
									<p></p>
								</td></tr>
						</table>
						
						</td>
                     </tr -->

					 <tr>
					 <td class='ariva'>
					 	<font class='footnote'>This message is automatically generated by the ARA system, and is not intended for reply.</font>
					</td></tr>
                  </table>
                  
               </td>
               
            </tr>
         </table>
         
      </td>
   </tr>
</table>

</body>
</html>
">
	
</cfoutput>
<cfmail to="anna.e.huang@hii.com" type="HTML" from="ARA@hii-tsd.com" subject="#subject#">#message#</cfmail>